# Generated by Django 6.0.2 on 2026-03-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Ordered Item",
                "verbose_name_plural": "Ordered Items",
            },
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.FloatField(),
        ),
    ]
