# Generated by Django 6.0.2 on 2026-03-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_category_name_alter_product_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
