# Generated by Django 6.0.2 on 2026-03-13 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_category_options_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
    ]
