# Generated by Django 6.0.2 on 2026-03-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.FloatField(),
        ),
    ]
