# Generated by Django 6.0.2 on 2026-03-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=10),
        ),
    ]
